PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "migrations" ("id" integer primary key autoincrement not null, "migration" varchar not null, "batch" integer not null);
INSERT INTO migrations VALUES(1,'0001_01_01_000000_create_users_table',1);
INSERT INTO migrations VALUES(2,'0001_01_01_000001_create_cache_table',1);
INSERT INTO migrations VALUES(3,'0001_01_01_000002_create_jobs_table',1);
INSERT INTO migrations VALUES(4,'2026_06_02_154527_create_pelanggans_table',1);
INSERT INTO migrations VALUES(5,'2026_06_02_154527_create_teknisis_table',1);
INSERT INTO migrations VALUES(6,'2026_06_02_154529_create_servis_table',1);
INSERT INTO migrations VALUES(7,'2026_06_02_154530_create_riwayat_statuses_table',1);
CREATE TABLE IF NOT EXISTS "users" ("id" integer primary key autoincrement not null, "name" varchar not null, "email" varchar not null, "email_verified_at" datetime, "password" varchar not null, "role" varchar not null default 'pelanggan', "remember_token" varchar, "created_at" datetime, "updated_at" datetime);
INSERT INTO users VALUES(1,'Admin Bengkel','admin@bengkel.com',NULL,'$2y$12$hti36BM7rTTz5b5vz9LEK.WpRkcpqxrnX..kEBzyjNOUNbnxjZi/e','admin',NULL,'2026-06-02 16:11:38','2026-06-02 16:11:38');
CREATE TABLE IF NOT EXISTS "password_reset_tokens" ("email" varchar not null, "token" varchar not null, "created_at" datetime, primary key ("email"));
CREATE TABLE IF NOT EXISTS "sessions" ("id" varchar not null, "user_id" integer, "ip_address" varchar, "user_agent" text, "payload" text not null, "last_activity" integer not null, primary key ("id"));
INSERT INTO sessions VALUES('i5Nonn2HGLL7Doax1bKra8Dt2AGBr4VgjG3LaCAH',1,'127.0.0.1','Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Safari/537.36','eyJfdG9rZW4iOiJXNTRoNWNZZ3FkUVJrZG5CSjV3UlV6a1BOSHJpNVFJUUUzY080VDNtIiwiX3ByZXZpb3VzIjp7InVybCI6Imh0dHA6XC9cLzEyNy4wLjAuMTo4MDAwXC9hZG1pblwvdGVrbmlzaSIsInJvdXRlIjoiYWRtaW4udGVrbmlzaS5pbmRleCJ9LCJfZmxhc2giOnsib2xkIjpbXSwibmV3IjpbXX0sImxvZ2luX3dlYl81OWJhMzZhZGRjMmIyZjk0MDE1ODBmMDE0YzdmNThlYTRlMzA5ODlkIjoxfQ==',1780416793);
CREATE TABLE IF NOT EXISTS "cache" ("key" varchar not null, "value" text not null, "expiration" integer not null, primary key ("key"));
CREATE TABLE IF NOT EXISTS "cache_locks" ("key" varchar not null, "owner" varchar not null, "expiration" integer not null, primary key ("key"));
CREATE TABLE IF NOT EXISTS "jobs" ("id" integer primary key autoincrement not null, "queue" varchar not null, "payload" text not null, "attempts" integer not null, "reserved_at" integer, "available_at" integer not null, "created_at" integer not null);
CREATE TABLE IF NOT EXISTS "job_batches" ("id" varchar not null, "name" varchar not null, "total_jobs" integer not null, "pending_jobs" integer not null, "failed_jobs" integer not null, "failed_job_ids" text not null, "options" text, "cancelled_at" integer, "created_at" integer not null, "finished_at" integer, primary key ("id"));
CREATE TABLE IF NOT EXISTS "failed_jobs" ("id" integer primary key autoincrement not null, "uuid" varchar not null, "connection" varchar not null, "queue" varchar not null, "payload" text not null, "exception" text not null, "failed_at" datetime not null default CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS "pelanggans" ("id" integer primary key autoincrement not null, "user_id" integer not null, "no_hp" varchar not null, "alamat" text not null, "created_at" datetime, "updated_at" datetime, foreign key("user_id") references "users"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "teknisis" ("id" integer primary key autoincrement not null, "nama" varchar not null, "no_hp" varchar not null, "spesialisasi" varchar not null, "status_aktif" tinyint(1) not null default '1', "created_at" datetime, "updated_at" datetime);
INSERT INTO teknisis VALUES(1,'zikri','0856778752627','laptop',1,'2026-06-02 16:12:51','2026-06-02 16:12:51');
CREATE TABLE IF NOT EXISTS "servis" ("id" integer primary key autoincrement not null, "kode_servis" varchar not null, "pelanggan_id" integer not null, "teknisi_id" integer, "nama_perangkat" varchar not null, "jenis_kerusakan" text not null, "status" varchar not null default 'antri', "estimasi_biaya" numeric not null, "biaya_final" numeric, "catatan_teknisi" text, "tgl_masuk" datetime not null default CURRENT_TIMESTAMP, "tgl_estimasi_selesai" date not null, "tgl_selesai" datetime, "deleted_at" datetime, "created_at" datetime, "updated_at" datetime, foreign key("pelanggan_id") references "pelanggans"("id") on delete cascade, foreign key("teknisi_id") references "teknisis"("id") on delete set null);
CREATE TABLE IF NOT EXISTS "riwayat_status" ("id" integer primary key autoincrement not null, "servis_id" integer not null, "status_lama" varchar, "status_baru" varchar not null, "catatan" text, "changed_by" integer not null, "created_at" datetime, "updated_at" datetime, foreign key("servis_id") references "servis"("id") on delete cascade, foreign key("changed_by") references "users"("id") on delete cascade);
DELETE FROM sqlite_sequence;
INSERT INTO sqlite_sequence VALUES('migrations',7);
INSERT INTO sqlite_sequence VALUES('users',1);
INSERT INTO sqlite_sequence VALUES('teknisis',1);
CREATE UNIQUE INDEX "users_email_unique" on "users" ("email");
CREATE INDEX "sessions_user_id_index" on "sessions" ("user_id");
CREATE INDEX "sessions_last_activity_index" on "sessions" ("last_activity");
CREATE INDEX "cache_expiration_index" on "cache" ("expiration");
CREATE INDEX "cache_locks_expiration_index" on "cache_locks" ("expiration");
CREATE INDEX "jobs_queue_index" on "jobs" ("queue");
CREATE INDEX "failed_jobs_connection_queue_failed_at_index" on "failed_jobs" ("connection", "queue", "failed_at");
CREATE UNIQUE INDEX "failed_jobs_uuid_unique" on "failed_jobs" ("uuid");
CREATE UNIQUE INDEX "servis_kode_servis_unique" on "servis" ("kode_servis");
COMMIT;
